-- 01_create_schema.sql
-- Create employee table for demonstration

CREATE TABLE employees (
    emp_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_name     VARCHAR2(100),
    emp_role     VARCHAR2(50),
    emp_salary   NUMBER(10,2),
    emp_status   VARCHAR2(20)
);

